poloniex:
  rules:
    - btc_strat >= 0.000001
    - btc_ltc   <= 0.02
  credentials:
    key: ""
    secrets: ""

config:
  timeout: 10
  command: 
    - paplay 
    - /usr/share/sounds/freedesktop/stereo/phone-incoming-call.oga
